### PR TITLE
Display alerts on Tickets list (GLPI 10.1)

### PR DESCRIPTION
**Pull request by Rom1-B**
Alerts were not displayed on the ticket list, even with the "Show on helpdesk page" option enabled.

Need to add a hook in the core.

!23784

### CODE REVIEW

**Comment by stdglpi** [comment]
Hello @cedric-anne 

I was not able to create a new issue but I installed the last "News" plugin on the last GLPI version.

I have this following error when I want to go to the settings of the plugin 

`PHP Warning:  Undefined array key "all_items" in C:\inetpub\wwwroot\glpi\plugins\news\inc\alert_target.class.php on line 73`

thank you !

**Comment by DevJLuc** [comment]
hello,
After migration to GLPI 10 and plugin Alertes to 1.10.4, I can input only text description.  Rich text is missing.   
image

**Comment by michaelNFF** [comment]
Hello,

I have the same issue about rich text editor missing.

Regards.

**Comment by michaelNFF** [comment]
Hello @DevJLuc 

[Alert form: fix missing richtext editor](https://github.com/pluginsGLPI/news/pull/112/commits/9c4a06cb4282a2ba0774029ebe573f74350c9b35)

Regards

**Review by cedric-anne — APPROVED** [review]

**Pull request merged**
