### PR TITLE
use groups_id instead of id for Group_User query

### LINKED ISSUE #27: Targeted "Groups" don't show any news

### PR DESCRIPTION
**Pull request by flegastelois**
Fix for #27

### CODE REVIEW

**Comment by trasher** [comment]
Changes are OK, but your hotfix is not: you did not bump the version in the constant and the xml file ;)

**Comment by flegastelois** [comment]
I forgot to indicate the tag "WIP" in the title of the PR, sorry :)
I do the bump this morning, I hope so...

**Comment by trasher** [comment]
Ok, no problem; ping me when you're done ;)

**Comment by flegastelois** [comment]
Seems to be ok with my last commit ? @trasher

**Pull request closed without merging**
